import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header'
import Footer from './components/footer'
import './globals.css'
import { ReactQueryProvider } from './components/react-query-provider/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header></Header>
          <div className="container mx-auto">
            {children}
          </div>
          <Footer></Footer>
        </body>
      </html>
    </ReactQueryProvider>
  )
}
